# baseURL
@baseURL = http://localhost:3000
@baseURLAssembly = http://localhost:3000/api/v1/assembly

###
# Create new assembly
POST {{baseURLAssembly}}/
Content-Type: application/json

{
    "workerId": "4da2f516-9055-4b56-8ac8-3cabf78a3e99",
    "rawMaterialsArr": [{"id": "9ea3bbf2-8b0d-41a7-bcd8-0b5903f4b7de", "quantity": 50}]
}

###
# Get all assemblies
GET {{baseURLAssembly}}

###
# Get assembly by ID
GET {{baseURLAssembly}}/e57f4cc3-a72e-4062-be07-c004e3766c3d

###
# Delete raw material by ID
DELETE  {{baseURLAssembly}}/6d579026-cae8-4d54-b374-1b2b67a66f61

###
# Update raw material
PUT {{baseURLAssembly}}/6d579026-cae8-4d54-b374-1b2b67a66f61
Content-Type: application/json

{   
    "id": "6d579026-cae8-4d54-b374-1b2b67a66f61",
	"completed": true
}
