# baseURL
@baseURL = http://localhost:3000
@baseURLAssembly = http://localhost:3000/api/v1/assembly

###
# Create new assembly
POST {{baseURLAssembly}}/
Content-Type: application/json

{
    "workerId": "4da2f516-9055-4b56-8ac8-3cabf78a3e99",
    "rawMaterialsArr": [{"id": "9ea3bbf2-8b0d-41a7-bcd8-0b5903f4b7de", "quantity": 50}]
}

###
# Get all assemblies
GET {{baseURLAssembly}}

###
# Get assembly by ID
GET {{baseURLAssembly}}/fac933ec-df6b-40b6-82d1-9e4fdb47b6f8

###
# Delete assembly by ID
DELETE  {{baseURLAssembly}}/fac933ec-df6b-40b6-82d1-9e4fdb47b6f8

###
# Update assembly
PUT {{baseURLAssembly}}/fac933ec-df6b-40b6-82d1-9e4fdb47b6f8
Content-Type: application/json

{   
    "id": "fac933ec-df6b-40b6-82d1-9e4fdb47b6f8",
	"completed": false
}
