# baseURL
@baseURL = http://localhost:3000
@baseURLRawMaterial = http://localhost:3000/api/v1/raw

###
# Create new raw material
POST {{baseURLRawMaterial}}/
Content-Type: application/json

{
    "name": "cone",
    "type": "white",
	"quantity": 1000
}

###
# Get all raw material
GET {{baseURLRawMaterial}}?searchTerm=

###
# Get raw material by ID
GET {{baseURLRawMaterial}}/af2faff4-bd33-4624-a253-7dcefaa27902

###
# Delete raw material by ID
DELETE  {{baseURLRawMaterial}}/af2faff4-bd33-4624-a253-7dcefaa27902

###
# Update raw material
PUT {{baseURLRawMaterial}}/29cd7b6d-5752-4f57-bdea-f5024c172b3c
Content-Type: application/json

{   
    "id": "29cd7b6d-5752-4f57-bdea-f5024c172b3c",
	"type": "white"
}
