# baseURL
@baseURL = http://localhost:3000
@baseURLRawMaterial = http://localhost:3000/api/v1/raw

###
# Create new raw material
POST {{baseURLRawMaterial}}/
Content-Type: application/json

{
    "name": "Square",
    "type": "metal",
	"quantity": 1000
}

###
# Get all raw material
GET {{baseURLRawMaterial}}?searchTerm=

###
# Get raw material by ID
GET {{baseURLRawMaterial}}/1917f9fd-5100-49cf-9d0c-87cca4aa42a8

###
# Delete raw material by ID
DELETE  {{baseURLRawMaterial}}/1917f9fd-5100-49cf-9d0c-87cca4aa42a8

###
# Update raw material
PUT {{baseURLRawMaterial}}/1917f9fd-5100-49cf-9d0c-87cca4aa42a8
Content-Type: application/json

{   
    "id": "1917f9fd-5100-49cf-9d0c-87cca4aa42a8",
	"quantity": 1050
}
