# baseURL
@baseURL = http://localhost:3000
@baseURLRawMaterial = http://localhost:3000/api/v1/raw

###
# Create new raw material
POST {{baseURLRawMaterial}}/
Content-Type: application/json

{
    "name": "Diamond",
    "type": "acrylic",
	"quantity": 500
}

###
# Get all raw material
GET {{baseURLRawMaterial}}?searchTerm=metal

###
# Get raw material by ID
GET {{baseURLRawMaterial}}/e51e9ab4-1f58-4a36-96f2-5b4e1263d068

###
# Delete raw material by ID
DELETE  {{baseURLRawMaterial}}/e51e9ab4-1f58-4a36-96f2-5b4e1263d068

###
# Update raw material
PUT {{baseURLRawMaterial}}/e51e9ab4-1f58-4a36-96f2-5b4e1263d068
Content-Type: application/json

{   
    "id": "e51e9ab4-1f58-4a36-96f2-5b4e1263d068",
	"quantity": 350
}
