# baseURL
@baseURL = http://localhost:3000
@baseURLWorker = http://localhost:3000/api/v1/worker

###
# Create new raw material
POST {{baseURLWorker}}/
Content-Type: application/json

{
    "name": "Kanchan Ben",
    "phone": "+919988776655",
    "address": "123 Baker Street, London"
}

###
# Get all workers
GET {{baseURLWorker}}?searchTerm=kan

###
# Get workers by ID
GET {{baseURLWorker}}/896a09a4-de63-4177-9a77-d38087751992

###
# Delete raw material by ID
DELETE  {{baseURLWorker}}/896a09a4-de63-4177-9a77-d38087751992

###
# Update raw material
PUT {{baseURLWorker}}/896a09a4-de63-4177-9a77-d38087751992
Content-Type: application/json

{   
    "id": "896a09a4-de63-4177-9a77-d38087751992",
	"phone": "+919322404040"
}
