# baseURL
@baseURL = http://localhost:3000
@baseURLWorker = http://localhost:3000/api/v1/worker

###
# Create new raw material
POST {{baseURLWorker}}/
Content-Type: application/json

{
    "name": "Kanchan Ben",
    "phone": "+919988776655",
    "address": "123 Baker Street, London"
}

###
# Get all workers
GET {{baseURLWorker}}?searchTerm=kan

###
# Get workers by ID
GET {{baseURLWorker}}/54b78608-fcb0-4d58-adcd-40e093999589

###
# Delete raw material by ID
DELETE  {{baseURLWorker}}/54b78608-fcb0-4d58-adcd-40e093999589

###
# Update raw material
PUT {{baseURLWorker}}/54b78608-fcb0-4d58-adcd-40e093999589
Content-Type: application/json

{   
    "id": "54b78608-fcb0-4d58-adcd-40e093999589",
	"phone": "+919322404040"
}
